---
# NIRES config file
# Want overhead to calculate clock time, where should I get it? -- Sherry is on it, incorporate when available


defaults:
  slit: [18 arcsec, 0.55 arcsec]  # Width, length
  pixel_size: 0.0225 arcsec^2/pixel  # Check w/ Sherry, in her code this was s^2/px^2 but I think that's a typo... ?
  mode: spectroscopic
  binning: [1, 1]

  
dark_current: 0.13 electron / (pixel s)

read_noise: 15 sqrt(electron/pixel)  # Kind of a nonsense unit, but read noise is actually variance and needs to be squared later...
# Is this per pixel?? Check w/ Sherry and make sure!

throughput_path: throughput.txt  # Relative path to throughput file

slit_options: [ [0.55 arcsec, 18 arcsec] ]

custom_slits: false

spectral_resolution: 2700  # Spectral resolving power of instrument, defined as λ / Δλ

mode_options: [spectroscopic]

gain: 3.8 electron / adu

nonlinear_depth: 30000 adu  # Confirm number with Sherry

# Options for binning [spatial, spectral]
binning_options: [ [1,1] ]